### PR TITLE
Updated stylus dependencies to 0.54.8.

### PR DESCRIPTION
**Pull request by AlynxZhou**
Fix https://github.com/stylus/nib/issues/347, remove NodeJS 14 warnings.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
@xdan Is it possible to publish a new version of nib on npm that includes this commit? Thanks!

**Comment by iChenLei** [comment]
> https://www.npmjs.com/package/nib

Only @tj and @notslang hava the permission to publish `nib` package, @stevenjoezhang  I am so sorry, I can't solve this problem immediately, I must send email to `tj` or `slang` first.

**Comment by stevenjoezhang** [comment]
Thanks very much for your reply. `nib` is an important dependency of the blog framework Hexo and is used by many blog themes. I would appreciate if the package can be updated on npm.

**Comment by notslang** [comment]
@iChenLei - I looked though the commit log and it seems like we're just updating deps and test cases. If there's no new functionality I'll release the last 31 commits as a patch. Do you think that's good, or should this be a new minor version?

**Comment by iChenLei** [comment]
@notslang  https://github.com/stylus/nib/pull/350 I create a pr for ci, replace outdated travis-ci with github actions, and make `stylus` as `peerDependencies` and not limit version, semver is wildcard `*`.  please review. I think minor version is better `v1.2.0`, and please help me add this big change in `changelog`, this is important for nib user. thanks
> https://github.com/iChenLei/nib/actions/runs/1211720732 New CI is work as expected.

**Pull request merged**
